const mongoose = require('mongoose');
const MovieSchema = new mongoose.Schema({
    Action:{
        required:true,
        type:Boolean
    },
    Adventure:{
        required:true,
        type:Boolean
    },
    Animation:{
        required:true,
        type:Boolean
    },
    Biography:{
        required:true,
        type:Boolean
    },
    Thriller:{
        required:true,
        type:Boolean
    },
    Comedy:{
        required:true,
        type:Boolean
    },
    Crime:{
        required:true,
        type:Boolean
    },
    Documentary:{
        required:true,
        type:Boolean
    },
    Drama:{
        required:true,
        type:Boolean
    },
    Family:{
        required:true,
        type:Boolean
    },
    Fantasy:{
        required:true,
        type:Boolean
    },
    Horror:{
        required:true,
        type:Boolean
    },
    Mystery:{
        required:true,
        type:Boolean
    },
    Romance:{
        required:true,
        type:Boolean
    },
    SuperHero:{
        required:true,
        type:Boolean
    },
    ScienceFiction:{
        required:true,
        type:Boolean
    },
    Movie_Name:{
        required:true,
        type:String
    },
    Movie_Year:{
        required:true,
        type:Number
    },
    Uploader_Name:{
        required:true,
        type:String
    },
    IMDB_Rating:{
        required:true,
        type:Number
    },
    Tomatos_Rating:{
        required:true,
        type:Number
    },
    Metacritic_Rating:{
        required:true,
        type:Number
    },
    Age_Requirement:{
        required:true,
        type:Number
    },
    Trailer_Link:{
        required:true,
        type:String
    },
    Director_Link:{
        required:true,
        type:String
    },
    Casts:{
        required:true,
        type:String
    },
    Description:{
        required:true,
        type:String
    },
    Download_Link:{
        required:true,
        type:String
    },
    Subtitle_Link:{
        required:true,
        type:String
    },
    UploadDate:{
        required:true,
        type:String
    }
});
const MovieModel = mongoose.model('Movie',MovieSchema);
module.exports = MovieModel;